### ISSUE TITLE
itemStyle not getting pass to WheelCurvedPicker.Item

### ISSUE THREAD

**Issue by dgonzalezr** [pinguinjkeke/react-native-wheel-datepicker#4]
¿Could be possible to override default item style for android?

As per `WheelCurvedPicker.android.js` file, the item style seems to sets only the default values:

```
static defaultProps = {
    textSize: 26,
    itemSpace: 20,
    itemStyle: null,
    textColor: '#333',
  };
```

and there's no current way to dynamic override them, rather than changing the code directly.

**Comment by pinguinjkeke** [comment]
Hi @dgonzalezr!

You can adjust style with this props. itemStyle is legacy and will be deleted in next release as it has no effect.
```js
textColor: ColorPropType,
textSize: PropTypes.number,
itemSpace: PropTypes.number,
```

**Comment by dgonzalezr** [comment]
@pinguinjkeke great, thanks! I'll give it a try :-)
