### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rtrainer** [pinguinjkeke/react-native-wheel-datepicker#5]
Do I need to follow the instructions from the original component, i.e. adding stuff to the android project?

**Comment by pinguinjkeke** [comment]
Hello @rtrainer! I just updated repo README.md file. All you need to do is:
```
npm install --save react-native-wheel-datepicker
react-native link react-native-wheel-datepicker
```

**Comment by rtrainer** [comment]
Thank you.
